name: examples
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# <hello>
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flame: ^1.7.3
# </hello>

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# <text>
flutter:
  uses-material-design: true

  fonts:
    - family: DotGothic16
      fonts:
        - asset: assets/fonts/DotGothic16-Regular.ttf
# </text>
