name: examples
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# <hello>
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flame: ^1.8.0
# </hello>
# <physics>
  flame_forge2d: ^0.14.0
# </physics>
# <sound1>
  flame_audio: ^2.0.3
# </sound1>

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# <text>
flutter:
  uses-material-design: true

  fonts:
    - family: DotGothic16
      fonts:
        - asset: assets/fonts/DotGothic16-Regular.ttf
# </text>

# <sound2>
# <sprite>
  assets:
    - assets/images/
# </sprite>
    - assets/audio/
# </sound2>